### ISSUE TITLE
[v1.3.0] Feature roadmap

### ISSUE THREAD

**Issue by sktse** [sktse/SLCBInternationalHello#14]
# v1.3.0
## Request Description
- [x] Detect multi-word greetings - 1a25ced857234c3559581453667565a9c77efaa6
- [x] Add readme to pop-up to script settings UI - 6e26cfb92eed9b262e900d8f7d98dd3418246cef
- [ ] Update documentation to allow multi-word custom inputs
- [ ] Add username blacklist.
    - [ ] Avoids script saying hello back to other bots
- [ ] Add `o/` and `o/\` as greetings
   - [ ] Escape character issues?
- [ ] Read greetings from file (JSON, CSV, new line separated?)
- [ ] Add greeting --> Warro (Guernésiais)
- [ ] Redo how `ReloadSettings()` works.  Have it properly go through validated `settings.reload()`.

## Bug fixes
- [x] Fix initial settings loading - 47e8c86927151fa84c360e5b4b8c1cec14c1153a
- [ ] Properly escape backslash `\`
    - [ ] This is stopping `o/\` from working right now
    - [ ] The input free text fields are not escaped and is failing.
